name: quran_app
description: "Quran Learning App - Récitation, traduction, translittération, répétition espacée"
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  just_audio: ^0.9.36
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  path_provider: ^2.1.4
  path_provider_android: ^2.2.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

dependency_overrides:
  path_provider_android: 2.2.10
  path_provider_foundation: 2.4.0
